package cards;

public class EquitySquaredRanking {
    private static Hand ranking[] = new Hand[]{
        new Hand(new Card("Ah"), new Card("Ah")),
        new Hand(new Card("Kh"), new Card("Kh")),
        new Hand(new Card("Qh"), new Card("Qh")),
        new Hand(new Card("Jh"), new Card("Jh")),
        new Hand(new Card("Th"), new Card("Th")),
        new Hand(new Card("9h"), new Card("9h")),
        new Hand(new Card("Ah"), new Card("Kd")),
        new Hand(new Card("8h"), new Card("8h")),
        new Hand(new Card("Ah"), new Card("Qd")),
        new Hand(new Card("Ah"), new Card("Kh")),
        new Hand(new Card("Ah"), new Card("Jd")),
        new Hand(new Card("Ah"), new Card("Td")),
        new Hand(new Card("Kh"), new Card("Qd")),
        new Hand(new Card("Ah"), new Card("Qh")),
        new Hand(new Card("7h"), new Card("7h")),
        new Hand(new Card("Kh"), new Card("Jd")),
        new Hand(new Card("Ah"), new Card("Jh")),
        new Hand(new Card("Kh"), new Card("Td")),
        new Hand(new Card("Ah"), new Card("9d")),
        new Hand(new Card("Kh"), new Card("Qh")),
        new Hand(new Card("Ah"), new Card("Th")),
        new Hand(new Card("Qh"), new Card("Jd")),
        new Hand(new Card("Ah"), new Card("8d")),
        new Hand(new Card("6h"), new Card("6h")),
        new Hand(new Card("Kh"), new Card("Jh")),
        new Hand(new Card("Qh"), new Card("Td")),
        new Hand(new Card("Ah"), new Card("7d")),
        new Hand(new Card("Kh"), new Card("9d")),
        new Hand(new Card("Kh"), new Card("Th")),
        new Hand(new Card("Jh"), new Card("Td")),
        new Hand(new Card("Ah"), new Card("9h")),
        new Hand(new Card("Ah"), new Card("5d")),
        new Hand(new Card("Qh"), new Card("Jh")),
        new Hand(new Card("Ah"), new Card("6d")),
        new Hand(new Card("Qh"), new Card("9d")),
        new Hand(new Card("Ah"), new Card("4d")),
        new Hand(new Card("Ah"), new Card("8h")),
        new Hand(new Card("5h"), new Card("5h")),
        new Hand(new Card("Qh"), new Card("Th")),
        new Hand(new Card("Kh"), new Card("8d")),
        new Hand(new Card("Ah"), new Card("3d")),
        new Hand(new Card("Jh"), new Card("9d")),
        new Hand(new Card("Ah"), new Card("7h")),
        new Hand(new Card("Kh"), new Card("7d")),
        new Hand(new Card("Kh"), new Card("9h")),
        new Hand(new Card("Jh"), new Card("Th")),
        new Hand(new Card("Ah"), new Card("2d")),
        new Hand(new Card("Th"), new Card("9d")),
        new Hand(new Card("Qh"), new Card("8d")),
        new Hand(new Card("Kh"), new Card("6d")),
        new Hand(new Card("Ah"), new Card("5h")),
        new Hand(new Card("Ah"), new Card("6h")),
        new Hand(new Card("Qh"), new Card("9h")),
        new Hand(new Card("Kh"), new Card("5d")),
        new Hand(new Card("Jh"), new Card("8d")),
        new Hand(new Card("Ah"), new Card("4h")),
        new Hand(new Card("Kh"), new Card("8h")),
        new Hand(new Card("4h"), new Card("4h")),
        new Hand(new Card("Th"), new Card("8d")),
        new Hand(new Card("Kh"), new Card("4d")),
        new Hand(new Card("Qh"), new Card("7d")),
        new Hand(new Card("Ah"), new Card("3h")),
        new Hand(new Card("Jh"), new Card("9h")),
        new Hand(new Card("Kh"), new Card("7h")),
        new Hand(new Card("9h"), new Card("8d")),
        new Hand(new Card("Kh"), new Card("3d")),
        new Hand(new Card("Qh"), new Card("6d")),
        new Hand(new Card("Th"), new Card("9h")),
        new Hand(new Card("Ah"), new Card("2h")),
        new Hand(new Card("Jh"), new Card("7d")),
        new Hand(new Card("Qh"), new Card("8h")),
        new Hand(new Card("Kh"), new Card("6h")),
        new Hand(new Card("Kh"), new Card("2d")),
        new Hand(new Card("Qh"), new Card("5d")),
        new Hand(new Card("Th"), new Card("7d")),
        new Hand(new Card("Jh"), new Card("8h")),
        new Hand(new Card("Qh"), new Card("4d")),
        new Hand(new Card("Kh"), new Card("5h")),
        new Hand(new Card("9h"), new Card("7d")),
        new Hand(new Card("3h"), new Card("3h")),
        new Hand(new Card("8h"), new Card("7d")),
        new Hand(new Card("Th"), new Card("8h")),
        new Hand(new Card("Jh"), new Card("6d")),
        new Hand(new Card("Qh"), new Card("3d")),
        new Hand(new Card("Qh"), new Card("7h")),
        new Hand(new Card("Kh"), new Card("4h")),
        new Hand(new Card("Jh"), new Card("5d")),
        new Hand(new Card("9h"), new Card("8h")),
        new Hand(new Card("Th"), new Card("6d")),
        new Hand(new Card("Qh"), new Card("2d")),
        new Hand(new Card("Qh"), new Card("6h")),
        new Hand(new Card("Kh"), new Card("3h")),
        new Hand(new Card("9h"), new Card("6d")),
        new Hand(new Card("Jh"), new Card("7h")),
        new Hand(new Card("Jh"), new Card("4d")),
        new Hand(new Card("8h"), new Card("6d")),
        new Hand(new Card("7h"), new Card("6d")),
        new Hand(new Card("Qh"), new Card("5h")),
        new Hand(new Card("Kh"), new Card("2h")),
        new Hand(new Card("Th"), new Card("7h")),
        new Hand(new Card("Jh"), new Card("3d")),
        new Hand(new Card("2h"), new Card("2h")),
        new Hand(new Card("Th"), new Card("5d")),
        new Hand(new Card("9h"), new Card("7h")),
        new Hand(new Card("Qh"), new Card("4h")),
        new Hand(new Card("Jh"), new Card("2d")),
        new Hand(new Card("8h"), new Card("7h")),
        new Hand(new Card("9h"), new Card("5d")),
        new Hand(new Card("Th"), new Card("4d")),
        new Hand(new Card("6h"), new Card("5d")),
        new Hand(new Card("7h"), new Card("5d")),
        new Hand(new Card("8h"), new Card("5d")),
        new Hand(new Card("Jh"), new Card("6h")),
        new Hand(new Card("Qh"), new Card("3h")),
        new Hand(new Card("Th"), new Card("3d")),
        new Hand(new Card("Jh"), new Card("5h")),
        new Hand(new Card("Th"), new Card("6h")),
        new Hand(new Card("5h"), new Card("4d")),
        new Hand(new Card("Qh"), new Card("2h")),
        new Hand(new Card("Th"), new Card("2d")),
        new Hand(new Card("9h"), new Card("6h")),
        new Hand(new Card("6h"), new Card("4d")),
        new Hand(new Card("8h"), new Card("6h")),
        new Hand(new Card("7h"), new Card("6h")),
        new Hand(new Card("9h"), new Card("4d")),
        new Hand(new Card("Jh"), new Card("4h")),
        new Hand(new Card("7h"), new Card("4d")),
        new Hand(new Card("8h"), new Card("4d")),
        new Hand(new Card("9h"), new Card("3d")),
        new Hand(new Card("Jh"), new Card("3h")),
        new Hand(new Card("5h"), new Card("3d")),
        new Hand(new Card("Th"), new Card("5h")),
        new Hand(new Card("9h"), new Card("2d")),
        new Hand(new Card("6h"), new Card("5h")),
        new Hand(new Card("6h"), new Card("3d")),
        new Hand(new Card("Jh"), new Card("2h")),
        new Hand(new Card("9h"), new Card("5h")),
        new Hand(new Card("Th"), new Card("4h")),
        new Hand(new Card("7h"), new Card("5h")),
        new Hand(new Card("8h"), new Card("5h")),
        new Hand(new Card("7h"), new Card("3d")),
        new Hand(new Card("4h"), new Card("3d")),
        new Hand(new Card("8h"), new Card("3d")),
        new Hand(new Card("8h"), new Card("2d")),
        new Hand(new Card("Th"), new Card("3h")),
        new Hand(new Card("5h"), new Card("2d")),
        new Hand(new Card("5h"), new Card("4h")),
        new Hand(new Card("Th"), new Card("2h")),
        new Hand(new Card("6h"), new Card("2d")),
        new Hand(new Card("6h"), new Card("4h")),
        new Hand(new Card("4h"), new Card("2d")),
        new Hand(new Card("9h"), new Card("4h")),
        new Hand(new Card("7h"), new Card("2d")),
        new Hand(new Card("7h"), new Card("4h")),
        new Hand(new Card("8h"), new Card("4h")),
        new Hand(new Card("9h"), new Card("3h")),
        new Hand(new Card("3h"), new Card("2d")),
        new Hand(new Card("5h"), new Card("3h")),
        new Hand(new Card("9h"), new Card("2h")),
        new Hand(new Card("6h"), new Card("3h")),
        new Hand(new Card("4h"), new Card("3h")),
        new Hand(new Card("7h"), new Card("3h")),
        new Hand(new Card("8h"), new Card("3h")),
        new Hand(new Card("8h"), new Card("2h")),
        new Hand(new Card("5h"), new Card("2h")),
        new Hand(new Card("6h"), new Card("2h")),
        new Hand(new Card("4h"), new Card("2h")),
        new Hand(new Card("7h"), new Card("2h")),
        new Hand(new Card("3h"), new Card("2h"))    
    };
    
    
    /**
     * returns the ranking of a given hand in the equity squared table
     * 1 is the best, 
     * @param handToRank
     * @return
     */
    public static int getRank(Hand handToRank){
        int rank = 1;
        for(Hand hand : ranking){
            if(handToRank.isEqualIgnoringSuit(hand) && (hand.isSuited() == handToRank.isSuited())){
                return rank;
            }
            rank++;
        }
        
        return 0;
    }
}
